std_skills/Meta meta

# Defines which hand has to grasp: ['left', 'right'] in case of 2 arms.
# If not specified, the motion will be performed with 
# the available hand by default.
string hand

# TODO: maybe add a parameter to specify how much to close the gripper

---
std_skills/Result result

---
std_skills/Feedback feedback