# Goal
std_skills/Meta meta

string LEFT_HAND = "left"
string RIGHT_HAND = "right"
string DEFAULT_HAND = ""
# use one of the standard hand identifiers (LEFT_HAND, RIGHT_HAND, DEFAULT_HAND)
# or use a custom string for implementation-specific end-effectors.
# an empty string is equivalent to DEFAULT_HAND (the actual default end-effector is implementation-specific)
string hand

# Gripper action. Insert an INT: 0 to CLOSE the gripper, 1 to OPEN it. 
# If a value that is not Integer or in [0, 1] will be set to Default. 
# Default = 'CLOSE'

int32 CLOSE = 0
int32 OPEN  = 1
int32 action


# 'closing_position' defines the closing position of the gripper if specified.  
# range: [0.0, 1.0] --> 0=Closed; 1=Open (gripper independent)
# If values outside range are given, 'DEFAULT_CLOSING_POSITION' it is going to be used.
float64 DEFAULT_CLOSING_POSITION = 0.0
float64 closing_position
---
# Result
std_skills/Result result
---
# Feedback
std_skills/Feedback feedback
