# Goal
std_skills/Meta meta

# use one of the standard side identifiers (LEFT_SIDE, RIGHT_SIDE, DEFAULT_SIDE)
# or use a custom string for implementation-specific end-effectors.
# an empty string is equivalent to DEFAULT_SIDE (the actual default end-effector is implementation-specific)
string LEFT_SIDE = "left"
string RIGHT_SIDE = "right"
string DEFAULT_SIDE = ""
string side

# Gripper action. Insert an INT: 0 to CLOSE the gripper, 1 to OPEN it. 
# If a value that is not Integer or in [0, 1] will be set to Default. 
# Default = 'CLOSE'
int8 CLOSE = 0
int8 OPEN  = 1
int8 action

---
# Result
std_skills/Result result
---
# Feedback
std_skills/Feedback feedback
