# Goal
std_skills/Meta meta

string LEFT_HAND = "left"
string RIGHT_HAND = "right"
string DEFAULT_HAND = ""
# use one of the standard hand identifiers (LEFT_HAND, RIGHT_HAND, DEFAULT_HAND)
# or use a custom string for implementation-specific end-effectors.
# an empty string is equivalent to DEFAULT_HAND (the actual default end-effector is implementation-specific)
string hand

# Gripper action. Insert an INT: 0 to CLOSE the gripper, 1 to OPEN it. 
# If a value that is not Integer or in [0, 1] will be set to Default. 
# Default = 'CLOSE'

int32 CLOSE = 0
int32 OPEN  = 1
int32 action

# TODO: maybe add a parameter to specify how much to close the gripper
---
# Result
std_skills/Result result
---
# Feedback
std_skills/Feedback feedback
